SELECT P.PRODUCT_ID, P.PRODUCT_NAME, sum(O.AMOUNT*P.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
AND to_char(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
group by P.PRODUCT_ID, P.PRODUCT_NAME
order by 3 desc, 1