select B.WRITER_ID, U.NICKNAME, SUM(B.PRICE) as TOTAL_SALES
from USED_GOODS_BOARD B, USED_GOODS_USER U
where B.WRITER_ID = U.USER_ID
and B.STATUS = 'DONE'
group by B.WRITER_ID, U.NICKNAME
having SUM(B.PRICE)>=700000
order by SUM(B.PRICE)