select U.USER_ID, U.NICKNAME, sum(B.PRICE) as TOTAL_SALES
from USED_GOODS_BOARD B, USED_GOODS_USER U
where B.WRITER_ID = U.USER_ID
and B.STATUS ='DONE'
group by U.USER_ID, U.NICKNAME
having sum(B.PRICE)>=700000
order by sum(B.PRICE)